defmodule Demo.Repo.Migrations.AddPageImageDimensions do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:pages) do
      add(:image_width, :bigint)
      add(:image_height, :bigint)
    end
  end

  def down do
    alter table(:pages) do
      remove(:image_height)
      remove(:image_width)
    end
  end
end
